### ISSUE TITLE
[Bug] Failed to register mod plugin

### ISSUE THREAD

**Issue by DWX12** [GoryMoon/HorsePower#40]
This is probably something on my end with recipes, but caught this bit in my log file and I'm not sure what I did or how to go about fixing it. I'm sure it probably has something to do with either syntax errors or config options I tweaked. Just a bit of insight on what the issue is would be helpful:

[03:25:56] [Client thread/ERROR] [jei]: Failed to register mod plugin: class se.gory_moon.horsepower.jei.HorsePowerPlugin
java.lang.IllegalArgumentException: Must have at least 1 tick per cycle.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[guava-21.0.jar:?]
	at mezz.jei.gui.TickTimer.<init>(TickTimer.java:13) ~[TickTimer.class:?]
	at mezz.jei.gui.elements.DrawableAnimated.<init>(DrawableAnimated.java:36) ~[DrawableAnimated.class:?]
	at mezz.jei.gui.GuiHelper.createAnimatedDrawable(GuiHelper.java:87) ~[GuiHelper.class:?]
	at se.gory_moon.horsepower.jei.chopping.ChoppingRecipeWrapper.<init>(ChoppingRecipeWrapper.java:47) ~[ChoppingRecipeWrapper.class:?]
	at se.gory_moon.horsepower.jei.chopping.ChoppingRecipeMaker.getChoppingRecipes(ChoppingRecipeMaker.java:31) ~[ChoppingRecipeMaker.class:?]
	at se.gory_moon.horsepower.jei.HorsePowerPlugin.register(HorsePowerPlugin.java:72) ~[HorsePowerPlugin.class:?]
	at mezz.jei.startup.JeiStarter.registerPlugins(JeiStarter.java:202) [JeiStarter.class:?]
	at mezz.jei.startup.JeiStarter.start(JeiStarter.java:73) [JeiStarter.class:?]
	at mezz.jei.startup.ProxyCommonClient.loadComplete(ProxyCommonClient.java:136) [ProxyCommonClient.class:?]
	at mezz.jei.JustEnoughItems.loadComplete(JustEnoughItems.java:55) [JustEnoughItems.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) [LoadController.class:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [guava-21.0.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [guava-21.0.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [guava-21.0.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [guava-21.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) [guava-21.0.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) [LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:752) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.init(Minecraft.java:535) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3931) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

Here's my config file currently:
https://hastebin.com/uniyidusol.pl

Many thanks.

**Comment by GoryMoon** [comment]
Think this might be what's causing the issue, the time needs to be at least 1, also looks like the time and meta might have been mixed up for that part. 
<img width="690" alt="Screenshot 2019-06-12 at 14 23 30" src="https://user-images.githubusercontent.com/987002/59351039-cc242680-8d1d-11e9-8579-986b6add3bfe.png">

**Comment by DWX12** [comment]
Thanks so much. I'll take a look at it when I have the chance to. Always nice to have an extra pair of eyes when troubleshooting code.

Edit:
Thank you again. Yeah, that's exactly what I did. Atleast know I'll have an idea of what to look for in the future next time I screw something up.
